# fly.toml app configuration file generated for trabajo-final on 2024-03-20T16:41:41-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trabajo-final'
primary_region = 'eze'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DATABASE_PATH = "/mnt/nuevo_volumen_nombre/db.sqlite3"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="nuevo_volumen_nombre"
  destination="/mnt/nuevo_volumen_nombre"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
